// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbEHRCFwKvG-vNsW_PcdMz29oddPbGkoE',
    appId: '1:649342354165:web:a83b38a9df15c0ff437bbc',
    messagingSenderId: '649342354165',
    projectId: 'flutter-chat-app-41645',
    authDomain: 'flutter-chat-app-41645.firebaseapp.com',
    storageBucket: 'flutter-chat-app-41645.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6MerOL3Ou9OC5eTubIXh2duaaLt_7tDk',
    appId: '1:649342354165:android:7b34222ca0937ec1437bbc',
    messagingSenderId: '649342354165',
    projectId: 'flutter-chat-app-41645',
    storageBucket: 'flutter-chat-app-41645.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2WPfCiCnq-M6oUH6lVUIo-lw40JxFaBc',
    appId: '1:649342354165:ios:29b7fcd6dc0bf506437bbc',
    messagingSenderId: '649342354165',
    projectId: 'flutter-chat-app-41645',
    storageBucket: 'flutter-chat-app-41645.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2WPfCiCnq-M6oUH6lVUIo-lw40JxFaBc',
    appId: '1:649342354165:ios:e7ecf3253879f05e437bbc',
    messagingSenderId: '649342354165',
    projectId: 'flutter-chat-app-41645',
    storageBucket: 'flutter-chat-app-41645.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
